---

#- hosts: stage
- hosts: all
  become: yes
  vars_files:
      - vars/main.yml

  roles:
      - aws-cli #requires boto which requires base
      - java8-oracle
      - geerlingguy.git
      - geerlingguy.nodejs

  tasks:
      - include: tasks/npm_modules.yml

#- hosts: development
